### ISSUE TITLE
Crashing when breaking Spawners in The Betweenlands dimension.

### ISSUE THREAD

**Issue by 3x1at1on** [TheCyberBrick/The-Betweenlands#1015]
#### Betweenlands version: 
3.5.10

#### Forge version:
14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:
Modpack MC Eternal 1.3.5b https://www.curseforge.com/minecraft/modpacks/minecraft-eternal

## Link to full crash log
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2020-04-10 21:35:28 BST
Description: Ticking player

java.lang.ClassCastException: thebetweenlands.common.tile.spawner.TileEntityMobSpawnerBetweenlands cannot be cast to net.minecraft.tileentity.TileEntityMobSpawner
    at com.minecolonies.coremod.event.EventHandler.onBlockBreak(EventHandler.java:381)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1654_EventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:851)
    at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:283)
    at net.minecraft.server.management.PlayerInteractionManager.updateBlockRemoving(PlayerInteractionManager.java:109)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:316)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642)
    at net.minecraft.world.World.updateEntities(World.java:1737)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
```
Detailed log: https://paste.dimdev.org/aberixunuq.makefile

#### How to reproduce:
Just breaking the mob spawner in the betweenlands dimension crashes the game (I tried Cragrock towers and Wight Fortresses). Other "non-betweenlands" spawners (vanilla and modded ones) are fine.

#### Expected result:
You should have the spawner breaking as normal with XP reward.

#### Actual result:
I have no idea what is causing this but it sounds like when I break the spawner it causes a Ticking Player crash.

**Comment by 3x1at1on** [comment]
Tested the mod on its own and there is no crash. I used two mods with Betweenlands that has things to do with spawners in general: Ender IO and Actually Additions and both did not cause the crash either. 
Interesting mechanic you have in the spawners that you need to kill all mobs spawned before the spawner gets destroyed. Wondering if there something in the mod pack interfering with mechanic as the spawner crystal stays green and do not turn light blue (Wight Fortress spawner) even when killing all mobs spawned out of it. But I am still at a loss to why this happened in my world with MC Eternal pack.

**Comment by TheCyberBrick** [comment]
Thanks for the report.
This crash is actually caused by MineColonies, you should report it to its authors instead.

**Comment by 3x1at1on** [comment]
You sir is a genius! Disabled minecolonies and it worked like a charm.
