### ISSUE TITLE
Crash when startup on 3.7.0 with Optifine

### ISSUE THREAD

**Issue by B-Wither** [TheCyberBrick/The-Betweenlands#1116]
## Versions
1.12.2
#### Betweenlands version:

3.7.0

#### Forge version:

forge-14.23.5.2854

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

OptiFine_1.12.2_HD_U_E3
jei_1.12.2-4.15.0.291.jar 
Quark-r1.6-179.jar      
AutoRegLib-1.3-32.jar  
foamfix-0.10.7-1.12.2.jar       
 journeymap-1.12.2-5.7.0.jar       
 QuarkOddities-1.12.2.jar       

## Link to full crash log

https://gist.github.com/B-Wither/cef765d3b0f0586b4397e5ddf90de452

#### How to reproduce:

1.Play Minecraft with Optifine.
2.Crashs when loading.

#### Expected result:

I can play this

#### Actual result:

Minecraft Crashed.

**Comment by PetasiGit** [comment]
Are you sure it’s an issue with optifine + BL? I can play 3.7.0 completely fine with optifine installed. Try removing all your other mods and see if the issue still persists.

**Comment by WeedTasteGood** [comment]
I also share the same problem. I have tried to use optifine alone but the game cannot even be opened. The error is 

The game crashed whilst stitching texture atlas
Error: java.lang.IndexOutOfBoundsException
Exit Code: -1

The whole error report is 👍 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.0-core.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/1/20 3:55 AM
Description: Stitching texture atlas

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Buffer.java:567)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:328)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:199)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:183)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:365)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.Buffer.checkBounds(Buffer.java:567)
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:328)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:199)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:183)

-- Texture being stitched together --
Details:
	Atlas path: textures
	Sprite: TextureAtlasSprite{name='thebetweenlands:particle/swarm_1_frame_0', frameCount=1, rotated=false, x=1072, y=944, height=16, width=16, u0=0.5234424, u1=0.5312451, v0=0.9218848, v1=0.9374902}
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:365)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:155)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 678890216 bytes (647 MB) / 2044723200 bytes (1950 MB) up to 7559184384 bytes (7209 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8109m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                              | Signature                                |
	|:----- |:--------------- |:------------ |:----------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2       | minecraft.jar                       | None                                     |
	| LCH   | mcp             | 9.42         | minecraft.jar                       | None                                     |
	| LCH   | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | thebetweenlands | 3.7.0        | TheBetweenlands-3.7.0-universal.jar | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 432.00
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

I am sorry if I have violated any rules. It's my first time using github (or maybe second time)

**Comment by B-Wither** [comment]
I tried to remove mods other than Optifine, but crashed.
So Optifine is causing crash, I think

**Comment by TheCyberBrick** [comment]
It's likely caused by the mipmapping settings; try disabling mip maps for now.

**Comment by xiongxiong1999** [comment]
It's been tested.
This is really an error caused by optifine.

**Comment by TheCyberBrick** [comment]
Update to v3.7.1, this should now be fixed.
