### ISSUE TITLE
Betweenlands crashing dont know whats causing this

### ISSUE THREAD

**Issue by ixRaiin** [TheCyberBrick/The-Betweenlands#1120]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!
 
Time: 2020-11-06 13:53:52 AST
Description: Initializing game
 
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:1002)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1955_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 627011712 bytes (597 MB) / 4093640704 bytes (3904 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 175 mods loaded, 175 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 
       | State | ID                                           | Version                  | Source                                               | Signature                                |
       |:----- |:-------------------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                                    | 1.12.2                   | minecraft.jar                                        | None                                     |
       | LCH   | mcp                                          | 9.42                     | minecraft.jar                                        | None                                     |
       | LCH   | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                                        | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | micdoodlecore                                |                          | minecraft.jar                                        | None                                     |
       | LCH   | xaerominimap_core                            | 1.12.2-1.0               | minecraft.jar                                        | None                                     |
       | LCH   | xaeroworldmap_core                           | 1.12.2-1.0               | minecraft.jar                                        | None                                     |
       | LCH   | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                        | None                                     |
       | LCH   | bnbgamingcore                                | 0.12.0                   | minecraft.jar                                        | None                                     |
       | LCH   | opencomputers|core                           | 1.7.5.192                | minecraft.jar                                        | None                                     |
       | LCH   | randompatches                                | 1.12.2-1.21.0.3          | randompatches-1.12.2-1.21.0.3.jar                    | None                                     |
       | LCH   | advancedcombat                               | 1.1.2                    | advancedcombat-1.1.2-[1.12].jar                      | None                                     |
       | LCH   | aiimprovements                               | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                      | None                                     |
       | LCH   | jei                                          | 4.15.0.296               | jei_1.12.2-4.15.0.296.jar                            | None                                     |
       | LCH   | ctm                                          | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                            | None                                     |
       | LCH   | chisel                                       | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                         | None                                     |
       | LCH   | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCH   | endercore                                    | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                          | None                                     |
       | LCH   | codechickenlib                               | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | redstoneflux                                 | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar              | None                                     |
       | LCH   | cofhcore                                     | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar                | None                                     |
       | LCH   | cofhworld                                    | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar               | None                                     |
       | LCH   | thermalfoundation                            | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar       | None                                     |
       | LCH   | thermalexpansion                             | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar        | None                                     |
       | LCH   | enderio                                      | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderiointegrationtic                        | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | mantle                                       | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
       | LCH   | quark                                        | r1.6-179                 | Quark-r1.6-179.jar                                   | None                                     |
       | LCH   | tconstruct                                   | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                     | None                                     |
       | LCH   | tesla                                        | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | theoneprobe                                  | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                          | None                                     |
       | LCH   | immersiveengineering                         | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                     | None                                     |
       | LCH   | alternatingflux                              | 0.12.2-2                 | alternatingflux-0.12.2-2.jar                         | None                                     |
       | LCH   | aoa3                                         | 3.3.6                    | AoA3-3.3.6.jar                                       | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCH   | placebo                                      | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                             | None                                     |
       | LCH   | apotheosis                                   | 1.12.4                   | Apotheosis-1.12.2-1.12.5.jar                         | None                                     |
       | LCH   | appleskin                                    | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
       | LCH   | thedragonlib                                 | 1.12.2-5.3.0             | thedragonlib-1.12.2-5.3.0.jar                        | None                                     |
       | LCH   | armorplus                                    | 1.12.2-11.28.0.69        | armorplus-1.12.2-11.28.0.69.jar                      | None                                     |
       | LCH   | autoreglib                                   | 1.3-32                   | AutoRegLib-1.3-32.jar                                | None                                     |
       | LCH   | avaritia                                     | 3.3.0                    | Avaritia-1.12.2-3.3.0.33-universal.jar               | None                                     |
       | LCH   | avaritiafurnace                              | 1.0.0                    | Avaritia_furnace-1.0.0-1.12.2.jar                    | None                                     |
       | LCH   | wanionlib                                    | 1.12.2-2.5               | WanionLib-1.12.2-2.5.jar                             | None                                     |
       | LCH   | avaritiaddons                                | 1.12.2-1.2               | Avaritiaddons-1.12.2-1.2.jar                         | None                                     |
       | LCH   | ichunutil                                    | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | backtools                                    | 7.0.1                    | BackTools-1.12.2-7.0.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | crafttweaker                                 | 4.1.20                   | CraftTweaker2-1.12-4.1.20.585.jar                    | None                                     |
       | LCH   | base                                         | 3.13.0                   | base-1.12.2-3.13.0.jar                               | None                                     |
       | LCH   | betteradvancements                           | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar               | None                                     |
       | LCH   | bettercaves                                  | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                         | None                                     |
       | LCH   | blockdrops                                   | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                          | None                                     |
       | LCH   | bnbgaminglib                                 | 2.17.6                   | BNBGamingLib-1.12.2-2.17.6.jar                       | None                                     |
       | LCH   | bookshelf                                    | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | spawnermod                                   | 1.0-1.12.2               | branders-enhanced-mob-spawners-v1.12.2-1.4.4.jar.jar | None                                     |
       | LCH   | buildcraftlib                                | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftcore                               | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftbuilders                           | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcrafttransport                          | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftsilicon                            | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftcompat                             | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftenergy                             | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftfactory                            | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | buildcraftrobotics                           | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
       | LCH   | cctweaked                                    | 1.89.2                   | cc-tweaked-1.12.2-1.89.2.jar                         | None                                     |
       | LCH   | computercraft                                | 1.89.2                   | cc-tweaked-1.12.2-1.89.2.jar                         | None                                     |
       | LCH   | cfm                                          | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                               | None                                     |
       | LCH   | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
       | LCH   | chiselsandbits                               | 14.33                    | chiselsandbits-14.33.jar                             | None                                     |
       | LCH   | chunkpregenerator                            | 2.1                      | Chunk+Pregenerator+V1.12-2.4E.jar                    | None                                     |
       | LCH   | randomtweaks                                 | 1.12.2-2.8.0.2           | randomtweaks-1.12.2-2.8.0.2.jar                      | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCH   | classicbar                                   | @VERSION@                | classicbar-0.5.4.jar                                 | None                                     |
       | LCH   | clumps                                       | 3.1.2                    | Clumps-3.1.2.jar                                     | None                                     |
       | LCH   | contenttweaker                               | 1.12.2-4.9.1             | ContentTweaker-1.12.2-4.9.1.jar                      | None                                     |
       | LCH   | conarm                                       | 1.2.5.9                  | conarm-1.12.2-1.2.5.9.jar                            | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | ctgui                                        | 1.0.0                    | CraftTweaker2-1.12-4.1.20.585.jar                    | None                                     |
       | LCH   | crafttweakerjei                              | 2.0.3                    | CraftTweaker2-1.12-4.1.20.585.jar                    | None                                     |
       | LCH   | cyclicmagic                                  | 1.20.3                   | Cyclic-1.12.2-1.20.4.jar                             | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
       | LCH   | movingworld                                  | 1.12-6.353               | movingworld-1.12-6.353-full.jar                      | None                                     |
       | LCH   | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar                  | None                                     |
       | LCH   | deathcounter                                 | 1.1.0                    | DeathCounter-1.12.2-1.1.0.jar                        | None                                     |
       | LCH   | gamestages                                   | 2.0.123                  | GameStages-1.12.2-2.0.123.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | dimstages                                    | 2.0.23                   | DimensionStages-1.12.2-2.0.23.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | discordcraft                                 | 1.0                      | DiscordCraft-2.0.jar                                 | None                                     |
       | LCH   | doggytalents                                 | 1.15.1.5                 | DoggyTalents-1.12.2-1.15.1.5.jar                     | None                                     |
       | LCH   | dragonmounts                                 | 1.12.2-1.6.3             | DragonMounts2-1.12.2-1.6.3.jar                       | None                                     |
       | LCH   | enchdesc                                     | 1.1.15                   | EnchantmentDescriptions-1.12.2-1.1.15.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | enderiobase                                  | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderioconduits                              | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderioconduitsappliedenergistics            | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | opencomputers                                | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar                 | None                                     |
       | LCH   | enderioconduitsopencomputers                 | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | refinedstorage                               | 1.6.15                   | refinedstorage-1.6.15.jar                            | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCH   | enderioconduitsrefinedstorage                | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderiointegrationforestry                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderiointegrationticlate                    | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | ftblib                                       | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                   | None                                     |
       | LCH   | enderiomachines                              | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderiopowertools                            | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                            | None                                     |
       | LCH   | enderstorage                                 | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | endreborn                                    | 0.3.1                    | EndReborn+III+[0.3.1].jar                            | None                                     |
       | LCH   | galacticraftcore                             | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar                | None                                     |
       | LCH   | galacticraftplanets                          | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar            | None                                     |
       | LCH   | mjrlegendslib                                | 1.12.2-1.2.0             | MJRLegendsLib-1.12.2-1.2.0.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | extraplanets                                 | 1.12.2-0.7.0             | ExtraPlanets-1.12.2-0.7.0.jar                        | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | extrautils2                                  | 1.0                      | extrautils2-1.12-1.9.9.jar                           | None                                     |
       | LCH   | fastfurnace                                  | 1.3.1                    | FastFurnace-1.12.2-1.3.1.jar                         | None                                     |
       | LCH   | fluxnetworks                                 | 4.0.14                   | fluxnetworks-1.12.2-4.0.15-32.jar                    | None                                     |
       | LCH   | forgelin                                     | 1.8.3                    | Forgelin-1.8.3.jar                                   | None                                     |
       | LCH   | forgemultipartcbe                            | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | microblockcbe                                | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar         | None                                     |
       | LCH   | minecraftmultipartcbe                        | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar         | None                                     |
       | LCH   | tschipplib                                   | 1.1.4                    | tschipplib-1.12.2-1.1.4.jar                          | None                                     |
       | LCH   | forgottenitems                               | 1.2.1                    | ForgottenItems+MC1.12.2+v1.2.1.jar                   | None                                     |
       | LCH   | ftbguides                                    | 2.0.0.52                 | FTBGuides-2.0.0.52.jar                               | None                                     |
       | LCH   | ftbutilities                                 | 5.4.1.130                | FTBUtilities-5.4.1.130.jar                           | None                                     |
       | LCH   | itemfilters                                  | 1.0.4.2                  | ItemFilters-1.0.4.2.jar                              | None                                     |
       | LCH   | ftbquests                                    | 1.9.0.12                 | FTBQuests-1.9.0.12.jar                               | None                                     |
       | LCH   | ftbtutorialmod                               | 1.0.0.11                 | FTBTutorialMod-1.0.0.11.jar                          | None                                     |
       | LCH   | galacticrafttweaker                          | 1.12.2-1.0.3             | GalacticraftTweaker-1.12.2-1.0.3.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | sereneseasons                                | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar            | None                                     |
       | LCH   | immersive_energy                             | 0.4.6                    | Immersive+Energy-1.12.2-0.4.6.jar                    | None                                     |
       | LCH   | immersivepetroleum                           | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                  | None                                     |
       | LCH   | inventoryhud                                 | 3.1.1                    | InventoryHud_1.12.2.forge-3.1.7.jar                  | None                                     |
       | LCH   | ironbackpacks                                | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                    | None                                     |
       | LCH   | ironchest                                    | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                      | None                                     |
       | LCH   | itemstages                                   | 2.0.49                   | ItemStages-1.12.2-2.0.49.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | jrftl                                        | 1.1                      | JRFTL[1.12.2]-1.1.jar                                | None                                     |
       | LCH   | jeresources                                  | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar              | None                                     |
       | LCH   | loadingscreens                               | 0.3.1                    | LoadingScreens-1.12.2-0.3.1.jar                      | None                                     |
       | LCH   | timecore                                     | 1.0.1.1                  | TimeCore-1.12.2-1.0.1.1.jar                          | None                                     |
       | LCH   | lootgames                                    | 1.0.3.1                  | LootGames-1.12.2-1.0.3.1.jar                         | None                                     |
       | LCH   | megaloot                                     | 0.2.40                   | megaloot-1.12.2-0.2.40.jar                           | None                                     |
       | LCH   | mousetweaks                                  | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                        | None                                     |
       | LCH   | mrtjpcore                                    | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar              | None                                     |
       | LCH   | mumboredstone                                | 0.3.3                    | mumboredstone-0.3.3.jar                              | None                                     |
       | LCH   | mycommands                                   | 1.12.2-01                | MyCommands-1.12.2-01.jar                             | None                                     |
       | LCH   | naturescompass                               | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                      | None                                     |
       | LCH   | nei                                          | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | oreexcavation                                | 1.4.150                  | OreExcavation-1.4.150.jar                            | None                                     |
       | LCH   | orestages                                    | 2.0.37                   | OreStages-1.12.2-2.0.37.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | performant                                   | 1.12.2-1.4               | performant-1.12.2-1.10.jar                           | None                                     |
       | LCH   | pitweaks                                     | 1.12-1.1.1               | PiTweaks-1.12-1.1.1.jar                              | None                                     |
       | LCH   | planetprogression                            | 1.12.2-0.4.4             | PlanetProgression-1.12.2-0.4.4.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCH   | projectred-core                              | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar                 | None                                     |
       | LCH   | projectred-integration                       | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
       | LCH   | projectred-transmission                      | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
       | LCH   | projectred-illumination                      | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-lighting.jar             | None                                     |
       | LCH   | projectred-expansion                         | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
       | LCH   | projectred-relocation                        | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
       | LCH   | projectred-transportation                    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
       | LCH   | quick_cheat_mod                              | Beta                     | Quick_Cheat_MOD_Beta_1.5.3_for_Minecraft_1.12.2.jar  | None                                     |
       | LCH   | randomthings                                 | 4.2.7.4                  | RandomThings-MC1.12.2-4.2.7.4.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | recipestages                                 | 1.1.3                    | RecipeStages-1.1.3.jar                               | None                                     |
       | LCH   | ruins                                        | 17.1                     | Ruins-1.12.2.jar                                     | None                                     |
       | LCH   | silentlib                                    | 2.2.18                   | SilentLib-1.12-2.2.18-100.jar                        | None                                     |
       | LCH   | spartanshields                               | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                      | None                                     |
       | LCH   | stg                                          | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                                 | None                                     |
       | LCH   | storagedrawers                               | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                      | None                                     |
       | LCH   | teslacorelib                                 | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | tinkersjei                                   | 1.2                      | tinkersjei-1.2.jar                                   | None                                     |
       | LCH   | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                  | None                                     |
       | LCH   | topaddons                                    | 1.12.2-1.13.0            | topaddons-1.12.2-1.13.0.jar                          | None                                     |
       | LCH   | torchmaster                                  | 1.8.4.84                 | torchmaster_1.12.2-1.8.4.84.jar                      | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCH   | traverse                                     | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                         | None                                     |
       | LCH   | triumph                                      | 3.19.2                   | Triumph-1.12.2-3.19.2.jar                            | None                                     |
       | LCH   | useless_sword                                | 1.2.2                    | UselessSword-1.12.2-V1.2.2.jar                       | None                                     |
       | LCH   | vanillafix                                   | 1.0.10-150               | VanillaFix-1.0.10-150.jar                            | None                                     |
       | LCH   | worldedit                                    | 6.1.10                   | worldedit-forge-mc1.12.2-6.1.10-dist.jar             | None                                     |
       | LCH   | worldeditcuife3                              | 3.0.5                    | WorldEdit-CUI-FE3-1.12.2-3.0.5.jar                   | None                                     |
       | LCH   | wrcbe                                        | 2.3.2                    | WR-CBE-1.12.2-2.3.2.33-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | xaerominimap                                 | 20.25.0                  | Xaeros_Minimap_20.25.0_Forge_1.12.jar                | None                                     |
       | LCH   | xaeroworldmap                                | 1.11.0                   | XaerosWorldMap_1.11.0_Forge_1.12.jar                 | None                                     |
       | LCH   | phosphor-lighting                            | 1.12.2-0.2.7             | phosphor-forge-mc1.12.2-0.2.7-universal.jar          | None                                     |
       | LCH   | thebetweenlands                              | 3.6.2                    | TheBetweenlands-3.6.2-universal.jar                  | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCH   | teslacorelib_registries                      | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                     | None                                     |
  Loaded coremods (and transformers): LoadingPlugin (RandomThings-MC1.12.2-4.2.7.4.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.3.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      MovingWorldCore (movingworld-1.12-6.353-full.jar)
 
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_20.25.0_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.11.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
 
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
 
                                      ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
                                        shadows.ApotheosisTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
 
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.12.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
 
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.2-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14736 Compatibility Profile Context FireGL 20.7.1 27.20.2001.8002' Renderer: 'AMD FirePro W5170M'
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            Authlib is : /C:/Users/Hp/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
 
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: The Betweenlands (thebetweenlands)
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: AMD FirePro W5170M GL version 4.6.14736 Compatibility Profile Context FireGL 20.7.1 27.20.2001.8002, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: !     �6�lDeos 2k Pack�r�6 [V2].zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by ixRaiin** [comment]
Advent of Ascension was causing this crash
