### ISSUE TITLE
Causes CTD When Used With Seasons Mod 

### ISSUE THREAD

**Issue by BearadactylPrime** [TheCyberBrick/The-Betweenlands#340]
So, there seems to be an issue with the Seasons mod; that's yet to be fixed by WeatherPony; it's been addressed, but so far there's been no fix issued on their end.

Seems the issue is wrapped around The Betweenlands Block Registry; here is the error log:

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 1/13/17 6:33 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access class thebetweenlands.blocks.BLBlockRegistry$8 from class weatherpony.partial.generated.thebetweenlands.blocks.BLBlockRegistry$8.proxyNum0
	at weatherpony.partial.generated.thebetweenlands.blocks.BLBlockRegistry$8.proxyNum0.call2(Unknown Source)
	at weatherpony.partial.generated.thebetweenlands.blocks.BLBlockRegistry$8.proxyNum0.call2(Unknown Source)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callProxy(HookListenerHelper.java:85)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:71)
	at weatherpony.seasons.pml.edits.block.BlockFlowerEdits$RegisterBlockIcons.call2(BlockFlowerEdits.java:86)
	at weatherpony.seasons.pml.edits.block.BlockFlowerEdits$RegisterBlockIcons.call2(BlockFlowerEdits.java:71)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.seasons.pml.edits.texturefixes.TextureRetrivalDuringCreation$RegisterBlockIcons.call2(TextureRetrivalDuringCreation.java:37)
	at weatherpony.seasons.pml.edits.texturefixes.TextureRetrivalDuringCreation$RegisterBlockIcons.call2(TextureRetrivalDuringCreation.java:21)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.partial.HookListenerHelper.distribute(HookListenerHelper.java:64)
	at weatherpony.partial.HookListenerHelperPool.distribute(HookListenerHelperPool.java:134)
	at weatherpony.partial.internal.GeneralHookManager.rigAndDistributeCall(GeneralHookManager.java:276)
	at thebetweenlands.blocks.BLBlockRegistry$8.func_149651_a(BLBlockRegistry.java)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:335)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:62)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at weatherpony.partial.generated.thebetweenlands.blocks.BLBlockRegistry$8.proxyNum0.call2(Unknown Source)
	at weatherpony.partial.generated.thebetweenlands.blocks.BLBlockRegistry$8.proxyNum0.call2(Unknown Source)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callProxy(HookListenerHelper.java:85)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:71)
	at weatherpony.seasons.pml.edits.block.BlockFlowerEdits$RegisterBlockIcons.call2(BlockFlowerEdits.java:86)
	at weatherpony.seasons.pml.edits.block.BlockFlowerEdits$RegisterBlockIcons.call2(BlockFlowerEdits.java:71)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.seasons.pml.edits.texturefixes.TextureRetrivalDuringCreation$RegisterBlockIcons.call2(TextureRetrivalDuringCreation.java:37)
	at weatherpony.seasons.pml.edits.texturefixes.TextureRetrivalDuringCreation$RegisterBlockIcons.call2(TextureRetrivalDuringCreation.java:21)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.partial.HookListenerHelper.distribute(HookListenerHelper.java:64)
	at weatherpony.partial.HookListenerHelperPool.distribute(HookListenerHelperPool.java:134)
	at weatherpony.partial.internal.GeneralHookManager.rigAndDistributeCall(GeneralHookManager.java:276)
	at thebetweenlands.blocks.BLBlockRegistry$8.func_149651_a(BLBlockRegistry.java)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:335)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:62)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6064564208 bytes (5783 MB) / 6407585792 bytes (6110 MB) up to 6407585792 bytes (6110 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCH	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCH	mcpml{10.1} [Partial Modification Loader [for Minecraft]] (PML_MinecraftApp.jar) 
	UCH	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCH	seasonsmod{pre-3.0beta13d5} [The Seasons Mod] ([1.7.10]TheSeasonsMod-pre-3.0beta13d5.jar) 
	UCH	seasonsmodac{1.0} [Additional Seasons Content] ([1.7.10]TheSeasonsMod-pre-3.0beta13d5.jar) 
	UCH	abyssalcraft{1.8.9} [AbyssalCraft] (AbyssalCraft-1.7.10-1.8.9.jar) 
	UCH	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-LATEST-1.7.10.jar) 
	UCH	antiqueatlas{4.2.4-1.7.10} [Antique Atlas] (antiqueatlas-4.2.4-1.7.10.jar) 
	UCH	hud{1.1b} [Better HUD] (Better HUD by NukeDuck [1.7.10][1.1b].zip) 
	UCH	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCH	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCH	druidry{2016.8.10-1.7.10} [§2Druidry] (druidry(2016.8.10.2)(1.7.10).jar) 
	UCH	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	etfuturum{1.4.1} [Et Futurum] (Et Futurum-1.4.1.jar) 
	UCH	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCH	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) 
	UCH	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCH	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCH	Roguelike{1.3.6.3} [Roguelike Dungeons] (roguelike-1.7.10-1.3.6.3.jar) 
	UCH	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCH	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCH	erebus{0.4.7} [Erebus] (TheErebus-0.4.7.jar) 
	UCH	TooMuchTime{2.4.0} [TooMuchTime] (TooMuchTime-1.7.10-2.4.0.B3-universal.jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCH	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCH	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.14008 Compatibility Profile Context 21.19.137.1' Renderer: 'AMD Radeon R7 200 Series'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.14008 Compatibility Profile Context 21.19.137.1, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge,pml'
	Type: Client (map_client.txt)
	Resource Packs: [AntiqueAtlasExtra.zip, John Smith Legacy 1.7.10 v1.2.24.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TheCyberBrick** [comment]
Hmm, the Seasons Mod seems to generate code that attemps to access our code somehow. That's not our responsibility or something we can fix on our side really.
