### ISSUE TITLE
[CRASH] bulb-capped mushroom + fortune

### ISSUE THREAD

**Issue by AlienXtream** [TheCyberBrick/The-Betweenlands#342]
breaking the stalks with a fortune tool causes CTD but breaking the tops with fortune does not

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 22/01/17 6:36 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thebetweenlands.blocks.plants.BlockBlubCappedMushroomStalk.func_149690_a(BlockBlubCappedMushroomStalk.java:77)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.Block.func_149636_a(Block.java:974)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at thebetweenlands.blocks.plants.BlockBlubCappedMushroomStalk.func_149690_a(BlockBlubCappedMushroomStalk.java:77)
	at net.minecraft.block.Block.func_149697_b(Block.java:648)
	at net.minecraft.block.Block.func_149636_a(Block.java:974)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(Unknown Source)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(Unknown Source)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1a4816bd
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by TheCyberBrick** [comment]
Thanks for reporting the bug 👍
