### ISSUE TITLE
[crash] boat mod incompatibility?

### ISSUE THREAD

**Issue by meelock** [TheCyberBrick/The-Betweenlands#352]
It appears as if The Betweenlands is not very happy when another mod tweaks boats (my thought) and returns a crash:

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
	at net.minecraftforge.client.model.ModelLoader.onPostBakeEvent(ModelLoader.java:1042)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:401)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

full log: [log](http://paste.ubuntu.com/24106138/)

**Comment by TheCyberBrick** [comment]
Already fixed in dev version
