### ISSUE TITLE
Issues with Mo'Creatures, CustomSpawner and other mod(s)

### ISSUE THREAD

**Issue by regix1** [TheCyberBrick/The-Betweenlands#404]
Description: Exception initializing level

java.lang.NullPointerException: Exception initializing level
	at drzhark.customspawner.EventHooks.onLivingSpawn(EventHooks.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventHooks_onLivingSpawn_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:185)
	at thebetweenlands.common.world.biome.spawning.MobSpawnHandler.populateChunk(MobSpawnHandler.java:510)
	at thebetweenlands.common.world.biome.spawning.MobSpawnHandler.populateChunk(MobSpawnHandler.java:290)
	at thebetweenlands.common.world.gen.ChunkGeneratorBetweenlands.func_185931_b(ChunkGeneratorBetweenlands.java:501)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOre(BiomeDecoratorBetweenlands.java:154)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOres(BiomeDecoratorBetweenlands.java:100)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:67)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorPatchyIslands.decorate(BiomeDecoratorPatchyIslands.java:12)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:51)
	at thebetweenlands.common.world.gen.ChunkGeneratorBetweenlands.func_185931_b(ChunkGeneratorBetweenlands.java:498)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOre(BiomeDecoratorBetweenlands.java:154)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOres(BiomeDecoratorBetweenlands.java:100)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:67)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorPatchyIslands.decorate(BiomeDecoratorPatchyIslands.java:12)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:51)
	at thebetweenlands.common.world.gen.ChunkGeneratorBetweenlands.func_185931_b(ChunkGeneratorBetweenlands.java:498)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOre(BiomeDecoratorBetweenlands.java:154)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOres(BiomeDecoratorBetweenlands.java:100)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:67)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorPatchyIslands.decorate(BiomeDecoratorPatchyIslands.java:12)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:51)
	at thebetweenlands.common.world.gen.ChunkGeneratorBetweenlands.func_185931_b(ChunkGeneratorBetweenlands.java:498)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOre(BiomeDecoratorBetweenlands.java:154)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.generateOres(BiomeDecoratorBetweenlands.java:100)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:67)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorMarsh.decorate(BiomeDecoratorMarsh.java:14)
	at thebetweenlands.common.world.gen.biome.decorator.BiomeDecoratorBetweenlands.decorate(BiomeDecoratorBetweenlands.java:51)
	at thebetweenlands.common.world.gen.ChunkGeneratorBetweenlands.func_185931_b(ChunkGeneratorBetweenlands.java:498)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:254)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.World.func_175623_d(World.java:223)
	at com.pam.harvestcraft.blocks.blocks.BlockBaseGarden.func_176196_c(BlockBaseGarden.java:105)
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generateGarden(BushWorldWorldGen.java:72)
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generate(BushWorldWorldGen.java:41)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:543)
	at com.pam.harvestcraft.worldgen.LogFruitTreeGen.func_180709_b(LogFruitTreeGen.java:54)
	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:154)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:227)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:543)
	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:118)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.World.func_175623_d(World.java:223)
	at com.pam.harvestcraft.blocks.blocks.BlockBaseGarden.func_176196_c(BlockBaseGarden.java:105)
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generateGarden(BushWorldWorldGen.java:72)
	at com.pam.harvestcraft.worldgen.BushWorldWorldGen.generate(BushWorldWorldGen.java:41)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:969)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.World.func_175623_d(World.java:223)
	at net.minecraft.world.World.func_184141_c(World.java:203)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:67)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:951)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:873)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:801)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:767)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3485)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

**Comment by regix1** [comment]
It crashes with this everytime I start the server. I tried resetting the world but still nothing.

**Comment by theishiopian** [comment]
try removing mo creatures and custom spawner and see if it persists.

**Comment by regix1** [comment]
When I remove Custom Spawner and Mo'Creatures it works. I would like to use these mods tho if I can.

**Comment by regix1** [comment]
I also found this issue with Pam's Havestcraft. 

java.lang.Error
	at net.minecraft.world.chunk.BlockStateContainer.func_186013_a(BlockStateContainer.java:84)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_177484_a(ExtendedBlockStorage.java:63)
	at net.minecraft.world.chunk.Chunk.fill(Chunk.java:2821)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_185932_a(SpongeChunkGenerator.java:278)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:140)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:543)
	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:163)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:543)
	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:153)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3076)
	at net.minecraft.world.gen.feature.WorldGenAbstractTree.isReplaceable(WorldGenAbstractTree.java:543)
	at com.pam.harvestcraft.worldgen.FruitTreeGen.func_180709_b(FruitTreeGen.java:62)
	at com.pam.harvestcraft.blocks.growables.BlockPamSapling.worldGenTrees(BlockPamSapling.java:152)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generateFruitTree(FruitTreeWorldGen.java:237)
	at com.pam.harvestcraft.worldgen.FruitTreeWorldGen.generate(FruitTreeWorldGen.java:128)
	at net.minecraftforge.fml.common.registry.GameRegistry.redirect$onGenerateWorld$zzd000(GameRegistry.java:665)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zop000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by regix1** [comment]
It makes it so when you fly around for a bit, and load a new chunk it will try to generate the Fruit Tree but it can't because its the BetweenLands world so then the server crashes.

**Comment by regix1** [comment]
I have been doing some testing, and it doesn't look like the mods are causing it because on my server I'm using "[Sponge](https://www.spongepowered.org/)" or in other terms "[SpongeForge](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2)" I ran the server with Mo'creatures the CreatureSpawner mod that is needed for Mo'Creatures and HarvestCraft, and it worked just fine with no issues. I then put in "SpongeForge" and that when I started getting the loading error in the console and then the game would crash.

**Comment by regix1** [comment]
Could you make this mod Compatible with Sponge?

**Comment by theishiopian** [comment]
Please keep the issue focused on one problem. For other problems, make separate issues.

**Comment by vadis365** [comment]
This is a year old nearly - closing.
