### ISSUE TITLE
NoClassDefFoundError when using Item Stages on Betweenlands' Items when on Server

### ISSUE THREAD

**Issue by justinrusso** [TheCyberBrick/The-Betweenlands#462]
I assume this is caused by client-side code being called on the server
Script:
```
var modIDs as string[] = [
	"thebetweenlands"
];

for id in modIDs {
    for item in loadedMods[id].items {
        mods.ItemStages.addItemStage("two", item);
    }
}
```

Crafttweaker.log:
https://gist.github.com/Darkosto/6eab269c320f892158088b15360bdf7b#file-gistfile1-txt-L7170

**Comment by GoryMoon** [comment]
Yeah, looks like an issue with calling client code on server, it's an easy fix. 
Will fix it when I get home.

**Comment by TheCyberBrick** [comment]
Oh the dreaded I18n strikes again ¯\_(ツ)_/¯

**Comment by GoryMoon** [comment]
No, the formater for aspect amount in the name of vials is in a client class

**Comment by GoryMoon** [comment]
```
java.lang.NoClassDefFoundError: thebetweenlands/client/handler/ScreenRenderHandler
	at thebetweenlands.common.item.herblore.ItemAspectVial.func_77653_i(ItemAspectVial.java:64)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.darkhax.itemstages.compat.crt.ActionAddItemRestriction.describe(ActionAddItemRestriction.java:67)
	at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:44)
	at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:131)
	at net.darkhax.itemstages.compat.crt.ItemStagesCrT.addItemStage(ItemStagesCrT.java:16)
	at Stage2_items.__script__(stage2.items.zs:14)
	at __ZenMain__.run(Stage2_items)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:149)
	at crafttweaker.runtime.CrTTweaker.load(CrTTweaker.java:56)
	at crafttweaker.CrafttweakerImplementationAPI.load(CrafttweakerImplementationAPI.java:115)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_464_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: thebetweenlands.client.handler.ScreenRenderHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 24 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 26 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more
```

**Comment by TheCyberBrick** [comment]
That too, but I noticed that some other items use the client sided I18n in getItemStackDisplayName which is not client side only
