### ISSUE TITLE
[BUG] [MC1.12.2] [TBL3.3.0] 

### ISSUE THREAD

**Issue by BastionNtB** [TheCyberBrick/The-Betweenlands#521]
I'm getting an error during load, it's not crashing, but I thought I'd report this anyway.

#### Betweenlands version:
TheBetweenlands-3.3.0-core
TheBetweenlands-3.3.0-universal

#### Forge version:
forge-1.12.2-14.23.2.2619

#### Singleplayer or Multiplayer:
Shows up in the server console

#### Installed mods:
AbyssalCraft-1.12.2-1.9.4.4.jar
albedo-0.1.3.jar
Aroma1997Core-1.12.2-1.3.0.2.jar
AromaBackup-1.12.2-2.1.1.3.jar
astralsorcery-1.12.2-1.8.5.jar
AutoRegLib-1.3-15.jar
Baubles-1.12-1.5.2.jar
BiomesOPlenty-1.12.2-7.0.1.2314-universal.jar
Botania+r1.10-353.jar
Chameleon-1.12-4.1.3.jar
ChickenChunks-1.12.2-2.4.1.71-universal.jar
Chisel-MC1.12-0.1.1.28.jar
chiselsandbits-14.13.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
CraftingCraft_1.12-6.1.3.jar
CraftingTweaks_1.12.1-8.1.6.jar
CraftTweaker2-1.12-4.1.4.jar
Cyclic-1.12.2-1.12.1.jar
Deadly+Monsters+1.71.jar
DoggyTalents-1.12-1.14.2.314-universal.jar
Dynmap-3.0-alpha-1-forge-1.12.2.jar
DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar
EnchantmentDescriptions-1.12.2-1.1.6.jar
EnderStorage-1.12.2-2.4.2.126-universal.jar
Farseek-1.12-2.2.3.jar
FastLeafDecay-v14.jar
Grue-1.12-1.3.5.jar
Guide-API-1.12-2.1.4-57.jar
harvestables-1.2.1.jar
hud-1.3.9-1.12.jar
Hwyla-1.8.23-B38_1.12.jar
infusedring-1.0.1.jar
InitialInventory-3.0.0.jar
IronBackpacks-1.12.2-3.0.5-6.jar
ironchest-1.12.2-7.0.37.822.jar
IvToolkit-1.3.3-1.12.jar
JAOPCA-1.12.2-2.2.6.71.jar
jei_1.12.2-4.8.5.147.jar
journeymap-1.12.2-5.5.2.jar
JustEnoughResources-1.12.2-0.8.5.27.jar
Mantle-1.12-1.3.1.21.jar
MCMultiPart-2.4.1.jar
MmmMmmMmmMmm-1.12-1.14.jar
mod_list.json
Morpheus-1.12-3.3.2.jar
MTLib-3.0.2.jar
MultiMine-1.12.2.jar
natura-1.12.2-4.3.2.42.jar
NetherEx-1.12-2.1.14.15.jar
NotEnoughItems-1.12.2-2.4.1.233-universal.jar
OpenBlocks-1.12.2-1.7.6.jar
OpenEye-1.12.1-0.8.jar
OpenModsLib-1.12.2-0.11.5.jar
OptiFine_1.12.2_HD_U_C9.jar
Pam's+HarvestCraft+1.12.2q.jar
plustic-6.3.6.2.jar
ProjectE-1.12-PE1.2.0.jar
Quark-r1.4-122.jar
RecurrentComplex-1.4.7.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
redstonepaste-mc1.12-1.7.5.jar
Reliquary-1.12.2-1.3.4.742.jar
RoguelikeDungeons-1.12.2-1.8.0.jar
SpartanShields-1.12.2-1.4.1.jar
stacksize-1.12.2-1.0.jar
StorageDrawers-1.12.2-5.3.4.jar
Streams-1.12-0.4.2.jar
SurvivalTweaks-5.0.4-1.12.2.jar
TConstruct-1.12.2-2.9.1.65.jar
The+Beneath-1.12.2-1.3.0.jar
TheBetweenlands-3.3.0-core.jar
TheBetweenlands-3.3.0-universal.jar
TinkerToolLeveling-1.12-1.0.3.jar
tombstone-2.5.2-1.12.jar
ToughAsNails-1.12.2-3.1.0.73-universal.jar
TrashSlot_1.12.1-8.4.6.jar
TreeChopper-1.12.2-1.2.4.jar
twilightforest-1.12.2-3.6.345-universal.jar
UnifiedItems-1.12.2-1.7.3-210.jar
WailaHarvestability-mc1.12-1.1.12.jar
Wawla-1.12.2-2.5.251.jar
WrapUp-1.12-1.1.3.jar

[1.12]+VersionChecker-1.3.0.jar
## Link to full crash log
It's not a crash, just an error that I'm curious about.

[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]: java.lang.ClassNotFoundException: thebetweenlands.common.registries.RecipeRegistry
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at java.lang.ClassLoader.loadClass(Unknown Source)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at java.lang.Class.forName0(Native Method)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at java.lang.Class.forName(Unknown Source)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at thelm.oredictinit.compat.CompatTheBetweenlands.register(CompatTheBetweenlands.java:17)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_494_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_249_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
[19:24:09] [Server thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatTheBetweenlands:register:23]:         at java.lang.Thread.run(Unknown Source)

#### How to reproduce:
Shows up upon server load, not sure if it's important or not.

#### Expected result:
Just looking to get rid of all errors

**Comment by TheCyberBrick** [comment]
That's JAOPCA doing something. It tries to register our oredict entries but since pur mod does that by default now it doesn't really matter, so you can just ignore this
